### PR TITLE
Feature/allow load options

### LINKED ISSUE #34: Please Export / Expose GoogleProtoFilesRoot
Please see [here](https://github.com/dcodeIO/protobuf.js/issues/704#issuecomment-382921183)  for context. 

If there is a better way to pass parse [options](https://github.com/dcodeIO/protobuf.js/blob/master/src/parse.js#L41-L62) down to protobufjs please let me know.

### PR DESCRIPTION
**Pull request by nmccready**
Fixes #34

- [x] Tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thank you for this!

@landrito WDYT?

**Comment by nmccready** [comment]
As a side not I was tempted in fixing this [unit test](https://github.com/googleapis/nodejs-proto-files/blob/master/test/load.test.js#L35-L37) . There is no reason for the done callback as mocha supports promises. Therefore the code is redundant.

**Comment by JustinBeckwith** [comment]
@landrito this is getting a little moldy :) Can we merge it?

**Comment by landrito** [comment]
Ah sorry for the delay! Approved!

**Pull request merged**
