### PR TITLE
Release google-proto-files v0.20.0

### PR DESCRIPTION
**Pull request by alexander-fenster**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Making a dummy release just to update the included proto files with their latest versions, to unblock https://github.com/googleapis/gax-nodejs/pull/446 and https://github.com/googleapis/nodejs-redis/pull/139.

**Comment by callmehiphop** [comment]
Shouldn't this be a patch release? It doesn't look like any of the protos have changed.

**Comment by alexander-fenster** [comment]
@callmehiphop Between 0.19.0 and 0.20.0, there were a lot of updates in googleapis (included in the .tgz file in this package), which I don't really want to evaluate on being patches or new features. So making it a minor release, just to be on a safe side.

image

**Comment by alexander-fenster** [comment]
Can anyone please press the button? :)  @JustinBeckwith @stephenplusplus @callmehiphop @jkwlui @bcoe This is the first of the set of PRs to unblock redis generation.

**Comment by alexander-fenster** [comment]
Thanks Stephen!

**Comment by callmehiphop** [comment]
Oh my bad, I didn't realize those changes found their way here. I just checked this repos commit log

**Pull request merged**
